### ISSUE TITLE
Divisions/Categories Within a List

### ISSUE THREAD

**Issue by tycebrown** [Pertempto/Lists#17]
I was thinking the ability to divide items within a list may be useful. 

The completed code of this issue should include the functionality to:

 - Add categories to a list.
 - Add an item  to a certain category.
 - Move an item from one category to another.

**Comment by tycebrown** [comment]
Should I close this issue?

**Comment by Pertempto** [comment]
Sure. Or we can save it for the future and try a simpler implementation with a better design.
