### ISSUE TITLE
Add labels or tags

### ISSUE THREAD

**Issue by tycebrown** [Pertempto/Lists#19]
Add some way to tag or label lists and filter based on them.

© 2023 Addison Emig

**Comment by tycebrown** [comment]
Alright, so I have a couple ideas on how to implement this:

- **Using IsarLinks**: In this implementation, we would have a class that represents a label (maybe called `ListModelLabel`) and we would create an isar collection of labels. We would then add an `IsarLinks<ListModelLabel>` field to our `ListModel` class. 
  - Pros:
    - The relationship makes sense (`ListModel` has links to all its labels).
    - Labels can be added, updated, or removed from this `ListModel` without having to re-`put` any other part of this `ListModel` (or any non-edited label).
  - Cons:
    -  We would have to manage the `IsarLinks`. That means we would need to keep the `IsarLinks`'s cache up to date, which might be a headache, and make sure we `save()` the links each time we change them.
  - Additional notes:
    - We could use a `BackLink` (see [here](https://isar.dev/links.html#backlinks)) to find all `ListModel`s with a certain label. Just like a normal isar link, however, we would need to make sure its cache is up to date. 
    - Overall, this is a very similar to my first approach to searching in #24.
- **Using a List of label ids**: Just like in the links implementation, we would have a label class and an isar collection of labels. However, in this implementation, instead of storing an `IsarLinks<ListModelLabel>`, we would store a `List` of label ids.
  - Pros:
    - No need to manage an `IsarLinks` object. The label ids are saved whenever this `ListModel` is `put()`. No cache, no headaches.
    - Simple.
    - Querying would be easy and efficient if we used [indexes](https://isar.dev/indexes.html).
  - Cons:
    - Whenever a label is added or removed, the entire `ListModel` object has to be re-`put`
    - Checking to see if a `ListModel` has a specific `Id` is linear (unless we kept the labels sorted).  

I personally like the idea of simply storing a `List` of ids. I can't imagine a single list having much more than 20 labels, so I don't think there would be much of a performance hit, if any. It's less complex and would probably be easier to manage. 

Any other approaches? Considerations? Do you want me to run some tests to compare these implementations? I noticed a few _'seems like'_ and _'might be'_ statements, along with some untested or opinionated ones.

**Comment by Pertempto** [comment]
Another approach would be to create NO separate list of labels, and only store the labels for each list in the list as an array of strings. Then when a user goes to add a new label, the autocomplete list would be populated with the labels used by any lists. This would be much simpler than any of the other approaches. I don't think you need to overthink it.

If that doesn't make sense, I can try to explain in a different way. Each List in the app would have a field called `labels`, where that field was simply an array of strings. Each string would be a label applied to that list.

**Comment by tycebrown** [comment]
Where do you imagine the widget for filtering the lists based on labels will be? In a side sheet, modal or otherwise? At the top?

**Comment by Pertempto** [comment]
> Where do you imagine the widget for filtering the lists based on labels will be? In a side sheet, modal or otherwise? At the top?

One idea is that you could put a filter button  in the app bar, to the left of the settings button. Then the button would open a filter dialog.

Another idea is to add a `Row` at the very top of the body of `HomePage`, above all the `ListPreviewWidget`. This `Row` could contain some kind of indicator that showed the current label filter, along with a button to open the filter dialog.

The Google keep app has all the labels in a left side bar, and when you click a label in the sidebar, it filters the lists by that label. This method looks very nice, but would be a little more complicated to implement maybe.


Do it however you would like, these are just a few ideas! 😄
