### ISSUE TITLE
Make Checklist Creation Easier

### ISSUE THREAD

**Issue by Pertempto** [Pertempto/Lists#25]
If you want to add a bunch of checkbox items, you add the items, and the you have to go back to enable the checkbox type.  

What if each new item in the list took their `itemType` value from the last item in the list? Then the user just has to add the first checkbox item, and all the rest would automatically match it.

**Comment by Pertempto** [comment]
The changes merged in #21 improve this experience, but I think matching the `itemType` on new items will still save users a step. They don't have to toggle the switch in the dialog if it automatically takes the value from the previous item.

**Comment by tycebrown** [comment]
Ah, that makes sense!
