### ISSUE TITLE
Empty Items

### ISSUE THREAD

**Issue by Pertempto** [Pertempto/Lists#28]
The app lets you add empty items. Maybe it shouldn't? It is confusing to have empty lines in a list.

**Comment by tycebrown** [comment]
Should this issue also address adding lists with empty names?

**Comment by Pertempto** [comment]
> Should this issue also address adding lists with empty names?

If you would like, sure! Or create another issue to address that.  

In general, it is easier when issues are kept small, because then it is easier and quicker to implement and review the code.
