### ISSUE TITLE
Repeated Items

### ISSUE THREAD

**Issue by Pertempto** [Pertempto/Lists#32]
It would be useful to have the ability to "repeat" items in a list. The user would select a time and interval. For example, they could have a to do list with a "mow the yard" item that gets added every Wednesday at 4pm.

Many task management apps have this feature. Google Tasks or Microsoft To Do would be good apps to look at for an example

**Comment by tycebrown** [comment]
Should these repeat items have a different style? What should indicate a repeat item? Also, do you think these items add themselves on every repeat, or un-check themselves?

I imagine the user would go into the `EditItemDialog` and toggle a "repeat" `Switch`. Then, they would have the option to set the days of the week the item should repeat, along with the time (perhaps different for each day?).

**Comment by Pertempto** [comment]
> Should these repeat items have a different style? What should indicate a repeat item?

Look at those other apps for inspiration for styling. I don't really think they would need to have significantly different styling. Maybe a little icon or something.

>  Also, do you think these items add themselves on every repeat, or un-check themselves?

I think the easiest method would be to un-check themselves. If they are already unchecked then they have no change.

> I imagine the user would go into the EditItemDialog and toggle a "repeat" Switch. Then, they would have the option to set the days of the week the item should repeat, along with the time (perhaps different for each day?).

Yes this could work. How many use cases would you like to support? There could be different interval options, for example
* Daily (ox X amount of days)
    * User selects what time of day
* Weekly (or X amount of weeks)
    * User selects what day(s) of the week, along with the time of day.
* Monthly (or X amount of months)
    * User selects what day(s) of the month, along with the time of day.
* Yearly (or X amount of years)
    * User selects what month, day, time

Supporting all of these interval types is going to be complicated. Maybe for this issue you could start out simple, with only supporting one type. I would vote for the weekly interval type, because that's what I would use most 😁

**Comment by Pertempto** [comment]
![Screenshot_20230626-183300_Tasks.png](https://github.com/Pertempto/Lists/assets/17209828/68492cd3-66b0-4524-bea9-ee131f350290)

Here is the repeat dialog in Google Tasks. It looks like the options are pretty powerful

**Comment by Pertempto** [comment]
The time option could be optional. A user could choose not to select a time of day, and it would just un-check at 12:00am of that day.

**Comment by Pertempto** [comment]
![Screenshot_20230626-183730_Tasks.png](https://github.com/Pertempto/Lists/assets/17209828/f8edcac8-0857-43c8-a891-2cfdbc01a929)

It shows a little icon, along with an indication of the next repeat time. I like how simple it is

**Comment by Pertempto** [comment]
Your algorithm for repeating items could be something like this:

```
On startup:
Iterate through all items that have repeat configuration
    If item.scheduledTimestamp < now
    Then,
        Mark item as unchecked
        Update item.scheduledTimestamp based on repeat configuration
    Else,
        Set timer for now - item.scheduledTimestamp
        Timer callback:
            Mark item as unchecked
            Update item.scheduledTimestamp based on repeat configuration
```

With the startup algorithm, you ensure that you don't need to run any kind of background tasks to change the checked status at the exact right time. Instead you can change all the items that have passed their timestamp when the user starts the app.


I think you would only need to add two fields to your `Item` class:
* One field to track repeat configuration
    * Set the field to `null` for items that don't repeat
    * The repeat configuration could be stored in a separate object
* One field to track the next scheduled time
    * Just a simple date or timestamp

**Comment by tycebrown** [comment]
One problem I am coming against: say the user sets an item's repeat configuration. The app sets a timer to go off at the `scheduledTimeStamp`. Then, right before the timer should go off, the user changes the repeat configuration. Now, we have a problem: the timer is still set to go off according to the previous configuration. 

First, should I focus on this, or is this too minor and rare a situation?

Here are my two ideas for a solution:

- We store a (nullable or `late`) timer in each item (which isn't stored in the database) set to go off at the `scheduledTimeStamp`. Then, if the user changes the repeat config, we cancel, discard, and replace that timer. 
- Instead of having a timer for each item that is scheduled to go off in the future, we could simply have one timer that goes off every minute and checks to see if any repeating items are scheduled.

I am leaning towards the first idea. Is there any painfully obvious and simple solution that I'm missing?

**Comment by Pertempto** [comment]
Yeah, I think the first idea is the way to go. Store it in a nullable field.

**Comment by tycebrown** [comment]
Should the app give a little in-app notification (like a [snackbar](https://api.flutter.dev/flutter/material/SnackBar-class.html)) when an item repeats?

**Comment by Pertempto** [comment]
I don't think that would be very useful. Most items are going to repeat when a user isn't in the app.

**Comment by Pertempto** [comment]
@tycebrown don't forget to set the assignee before you work on an issue
