### ISSUE TITLE
Remove Bottom Sheet from Home Page

### ISSUE THREAD

**Issue by Pertempto** [Pertempto/Lists#34]
When a user wants to edit a list title, it takes a lot of taps. They have to
* Press and hold the list
* Tap the edit button in the bottom sheet
* Make changes
* Press Submit

It would be more efficient if we got rid of the bottom sheet and moved the delete button to the list setup dialog. Then a user could press and hold a list, and immediately have access to the setup dialog.

**Comment by tycebrown** [comment]
Do you think we should put the delete button in the actions of the dialog?

**Comment by Pertempto** [comment]
Yeah, in red text?

**Comment by tycebrown** [comment]
> Yeah, in red text?

Yeah.
