### ISSUE TITLE
Add a Proper App Icon

### ISSUE THREAD

**Issue by Pertempto** [Pertempto/Lists#35]
The app should use an actual icon, instead of the generic Flutter app icon.

@tycebrown what should it look like?

**Comment by Pertempto** [comment]
Here is an image editor that I've used before: https://boxy-svg.com

**Comment by tycebrown** [comment]
> @tycebrown what should it look like?

My idea isn't original or creative, but I was thinking something like the [list_alt icon](https://fonts.google.com/icons?selected=Material+Symbols+Outlined:list_alt:FILL@0;wght@400;GRAD@0;opsz@48&icon.query=list&icon.platform=ios) with a little pencil (or checkmark?) icon in the bottom right corner. What do you think?

**Comment by Pertempto** [comment]
That could work. Just don't copy the image file directly, draw your own. I think it could look a little better if you round the corners a bit.

**Comment by tycebrown** [comment]
This is my first attempt:

<img width="376" alt="image" src="https://github.com/Pertempto/Lists/assets/91034018/39d27d5c-5d95-45e0-bfab-ac8916dcd83b">

How would you recommend I change this?

**Comment by Pertempto** [comment]
It looks pretty good! It would be better to be a little more square. Use less bullet points and make the page wider.

Also, have you tested what this will look like as an Android icon? I'm guessing that the thin lines might be hard to see when the icon is smaller. I would recommend making the background some solid color with no borders. Then you can make the bullet point items a contrasting color to show up nice. You should also probably make the pencil two contrasting colors, with no outlines.

**Comment by tycebrown** [comment]
Here is the edited icon (click on it to see it in a new tab): 

![lists_app_icon](https://github.com/Pertempto/Lists/assets/91034018/78f02416-a0cf-41bd-a698-a067f3f6b0f0)

I finally tested it on android and thought it looked fairly decent, though a little small. You can see how it looks by running this branch's version of the app.

How do you think it should be further edited?

**Comment by Pertempto** [comment]
It looks pretty good! Please create a MR for this type of feedback discussion.

**Comment by Pertempto** [comment]
It is totally fine to create a draft MR to get early feedback on a branch that isn't complete.
