### ISSUE TITLE
Reorder items

### ISSUE THREAD

**Issue by Pertempto** [Pertempto/Lists#40]
I can't reorder my to-do list items

**Comment by tycebrown** [comment]
#44 (move checked items to bottom of list) has been completed and merged into main.

How do you think this should fit in with the ability to reorder items? Should the user be able to reorder checked items? Separately from the unchecked items?

I can't quite imagine a use for reordering checked items in the current state of the app, so I'm thinking that the user could only reorder unchecked items. What are your thoughts and what do you think would be most useful?

**Comment by Pertempto** [comment]
No, users should not be able to reorder checked items. I'm imagining that the checked items would retain the order they had before they were checked.

A tip for implementation:
- The way I would normally store this type of data in the DB is to give each `Item` an `order` field.
- The `order` field should be numeric, and you set it to the index of the item in the list, every time the user has re-ordered things
- Then when you load the data, you can just sort by the `order` field

Hopefully this is helpful! Let me know if you have any other questions.

**Comment by tycebrown** [comment]
> No, users should not be able to reorder checked items. I'm imagining that the checked items would retain the order they had before they were checked.

Sounds good, thank you!

> A tip for implementation:
> 
> * The way I would normally store this type of data in the DB is to give each `Item` an `order` field.
> * The `order` field should be numeric, and you set it to the index of the item in the list, every time the user has re-ordered things
> * Then when you load the data, you can just sort by the `order` field

Oh, that sounds much easier than what I had been trying to do :joy: Definitely helpful!
